let app,auth,db,currentUser=null,isAdmin=false,isSystemAdmin=false,formAssignments=[],formManagers=[],forms=[],responses=[],departments=[],members=[],memberAccounts=[],activeFormId='',editMode='new',editingId='',draftQuestions=[],editingResponseId='',memberEditMode='view',editingMemberId='',submissionLocksPrepared=false,loginPurpose='admin',formDirty=false;
const $=id=>document.getElementById(id);
const front=$('front'),frontMain=$('frontMain'),formStatus=$('formStatus'),admin=$('admin'),loginMask=$('loginMask'),loginBtn=$('loginBtn'),loginMsg=$('loginMsg'),adminUser=$('adminUser'),activeFormSelect=$('activeFormSelect'),activeFormLabel=$('activeFormLabel'),formsTable=$('formsTable'),resultsTable=$('resultsTable'),questionEditor=$('questionEditor');

function col(name){return db.collection(name)}
function doc(name,id){return col(name).doc(id)}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function attr(v){return esc(v)}
function normalizeEmail(value){return String(value||'').trim().toLowerCase()}
function memberDisplayName(member){return [member?.department||member?.departmentName||'',member?.name||''].filter(Boolean).join(' ')||member?.name||''}
function memberGoogleEmail(member){let account=memberAccounts.find(a=>a.memberId===member?.id||a.id===member?.id);return normalizeEmail(account?.email||member?.googleEmail||member?.googleAccount||member?.email||member?.gmail||'')}
function findMemberByGoogleEmail(email){let target=normalizeEmail(email);return target?members.find(m=>memberGoogleEmail(m)===target)||null:null}
function toast(message,type='info'){let t=$('toast');t.textContent=message;t.className='toast '+type;t.style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.style.display='none',2600)}
function notify(message,type='warn'){toast(message,type);return false}
let dialogResolve=null,dialogOptions={};
function openDialog({title='確認操作',message='',confirmText='確定',cancelText='取消',danger=false,inputLabel='',requiredText='',inputValue=''}){let mask=$('dialogMask'),inputWrap=$('dialogInputWrap'),input=$('dialogInput'),confirm=$('dialogConfirm');$('dialogTitle').textContent=title;$('dialogMessage').textContent=message;$('dialogCancel').textContent=cancelText;confirm.textContent=confirmText;confirm.className='btn '+(danger?'danger':'primary');dialogOptions={requiredText};inputWrap.style.display=inputLabel?'block':'none';inputWrap.firstChild.textContent=inputLabel||'確認文字';input.value=inputValue||'';mask.style.display='grid';if(inputLabel)setTimeout(()=>input.focus(),60);return new Promise(resolve=>{dialogResolve=resolve})}
function closeDialog(ok){let mask=$('dialogMask'),input=$('dialogInput'),required=dialogOptions.requiredText||'';if(ok&&required&&input.value!==required){toast('輸入內容不一致，請重新確認。','warn');input.focus();return}mask.style.display='none';let resolve=dialogResolve;dialogResolve=null;if(resolve)resolve(ok?{ok:true,value:input.value}:{ok:false,value:''})}
async function confirmDialog(message,title='確認操作',danger=false){let result=await openDialog({title,message,danger,confirmText:danger?'確認':'確定'});return !!result.ok}
async function inputConfirmDialog({title='確認操作',message='',requiredText='',danger=false}){let result=await openDialog({title,message,danger,inputLabel:'請輸入確認文字',requiredText,confirmText:danger?'確認刪除':'確定'});return result.ok?result.value:null}
async function showCopyDialog(title,value){await openDialog({title,message:'瀏覽器不允許自動複製，請從下方欄位複製。',inputLabel:'連結',inputValue:value,confirmText:'關閉',cancelText:'取消'});return value}
function setPageLoading(visible,text='處理中…'){let box=$('pageLoading');if(!box)return;box.hidden=!visible;let inner=box.querySelector('div');if(inner)inner.textContent=text}
function formatDeadline(value){if(!value)return '';let d=new Date(value);return Number.isNaN(d.getTime())?value:d.toLocaleString('zh-TW',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}
function formatAnyDate(value){if(!value)return '';let raw=value?.toDate?value.toDate():value;let d=raw instanceof Date?raw:new Date(raw);return Number.isNaN(d.getTime())?String(value||''):d.toLocaleString('zh-TW',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'})}
function formStartLabel(f){return formatAnyDate(f?.startAt||f?.openAt||f?.createdAt)||'未紀錄'}
function deadlinePassed(value){if(!value)return false;let d=new Date(value);return !Number.isNaN(d.getTime())&&d<new Date()}
function driveFileId(value){let v=String(value||'').trim();if(!v)return '';try{let u=new URL(v);if(!/(^|\.)drive\.google\.com$/i.test(u.hostname))return '';let pathMatch=u.pathname.match(/\/file\/d\/([^/]+)/i)||u.pathname.match(/\/d\/([^/]+)/i);return pathMatch?.[1]||u.searchParams.get('id')||''}catch(e){return''}}
function imageUrl(value){let v=String(value||'').trim();if(!v)return '';if(/^assets\/[\w./-]+$/i.test(v))return v;let driveId=driveFileId(v);if(driveId)return `https://drive.google.com/thumbnail?id=${encodeURIComponent(driveId)}&sz=w1600`;try{let u=new URL(v,location.href);return /^https?:$/.test(u.protocol)?u.href:''}catch(e){return''}}
function imagePreviewHtml(value,alt='圖片預覽'){let url=imageUrl(value);return url?`<img src="${attr(url)}" alt="${attr(alt)}" onerror="this.parentElement.innerHTML='<div class=&quot;imagePreviewError&quot;>圖片無法顯示，請確認 Google Drive 分享權限。</div>'">`:''}
function previewHeaderImage(){$('headerImagePreview').innerHTML=imagePreviewHtml($('formImageUrl').value,'頁首圖片預覽')}
function updateQuestionImage(i,value){draftQuestions[i].imageUrl=value;let preview=$('questionImagePreview_'+i);if(preview)preview.innerHTML=imagePreviewHtml(value,draftQuestions[i].title||'參考圖片預覽')}
function formRouteId(){let m=location.hash.match(/^#form\/([^/?#]+)/);return m?decodeURIComponent(m[1]):''}

async function init(){
  if(!window.firebase||typeof firebaseConfig==='undefined'||!firebaseConfig.apiKey){frontMain.innerHTML='<div class="successCard"><h2>尚未設定 Firebase</h2><p>請確認 js/config.js 已正確上傳。</p></div>';return}
  app=firebase.initializeApp(firebaseConfig);auth=firebase.auth();db=firebase.firestore();
  window.addEventListener('hashchange',applyRoute);
  window.addEventListener('beforeunload',e=>{if(formDirty){e.preventDefault();e.returnValue=''}});
  document.addEventListener('input',e=>{if($('editorPanel')?.contains(e.target))formDirty=true});
  document.addEventListener('change',e=>{if($('editorPanel')?.contains(e.target))formDirty=true});
  auth.onAuthStateChanged(async user=>{currentUser=user;isAdmin=false;isSystemAdmin=false;formAssignments=[];if(user){try{isSystemAdmin=await checkAdmin(user);formAssignments=await loadCurrentAssignments(user);isAdmin=isSystemAdmin||formAssignments.some(x=>x.enabled!==false)}catch(e){console.error(e)}if(isAdmin){let member=findMemberByGoogleEmail(user.email),name=memberDisplayName(member)||user.displayName||'後台使用者';if($('adminUserName'))$('adminUserName').textContent=name;adminUser.textContent=(user.email||'')+(isSystemAdmin?'・系統管理員':'');loginMask.style.display='none';await loadAdminData()}else if(loginPurpose==='response'){loginMask.style.display='none';await loadMemberAccounts()}else loginMsg.textContent='此帳號尚未被指派任何問卷權限，請聯絡系統管理員。'}else{memberAccounts=[]}applyRoute()});
  await loadPublicData();applyRoute();
}

async function checkAdmin(user){let direct=await doc('users',user.uid).get();if(direct.exists){let u=direct.data();if(u.enabled!==false&&String(u.role||'').toLowerCase()==='admin')return true}let q=await col('users').where('email','==',user.email).limit(1).get();if(q.empty)return false;let u=q.docs[0].data();return u.enabled!==false&&String(u.role||'').toLowerCase()==='admin'}
async function loadMemberAccounts(){if(!currentUser){memberAccounts=[];return}try{let snap=await col('memberAccounts').get();memberAccounts=snap.docs.map(x=>({id:x.id,...x.data()}))}catch(e){console.warn('讀取 Google 帳號對應失敗，請確認 v1.24 Firestore 規則已部署',e);memberAccounts=[]}}
async function normalizeExistingResponseIds(items){let changed=false,ids=new Set(items.map(x=>x.id));for(let r of items){if(!r.memberId)continue;let target=`${r.formId}__${r.memberId}`;if(ids.has(target))continue;let {id,...data}=r;try{await doc('universalResponses',target).set(data);await doc('universalResponses',id).delete();ids.add(target);changed=true}catch(e){console.warn('既有回覆防重複轉換失敗',e)}}return changed}
async function prepareSubmissionLocks(){try{let [responseSnap,lockSnap]=await Promise.all([col('universalResponses').get(),col('universalResponseLocks').get()]),items=responseSnap.docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>(b.submittedAt?.seconds||0)-(a.submittedAt?.seconds||0)),responseIds=new Set(items.map(x=>x.id)),lockIds=new Set(lockSnap.docs.map(x=>x.id)),handled=new Set();for(let r of items){if(!r.formId||!r.memberId)continue;let key=`${r.formId}__${r.memberId}`;if(handled.has(key))continue;handled.add(key);if(!responseIds.has(key)){let {id,...data}=r;await doc('universalResponses',key).set(data);await doc('universalResponses',id).delete();responseIds.add(key)}if(!lockIds.has(key)){await doc('universalResponseLocks',key).set({formId:r.formId,memberId:r.memberId,createdAt:firebase.firestore.FieldValue.serverTimestamp()});lockIds.add(key)}}}catch(e){console.warn('建立既有回覆鎖定紀錄失敗，請確認 v1.10 Firestore 規則',e)}finally{submissionLocksPrepared=true}}

function openAdmin(){loginPurpose='admin';history.pushState(null,'','#admin');applyRoute()}
function closeLogin(){loginMask.style.display='none';history.replaceState(null,'','#form/'+encodeURIComponent(activeFormId||''));applyRoute()}
async function loginGoogle(){if(!auth){loginMsg.textContent='登入服務尚未完成初始化，請重新整理頁面後再試一次。';return}loginBtn.disabled=true;loginBtn.textContent='登入處理中…';loginMsg.textContent='';try{let p=new firebase.auth.GoogleAuthProvider();p.setCustomParameters({prompt:'select_account'});await auth.signInWithPopup(p);if(loginPurpose==='admin'&&!isAdmin)loginMsg.textContent='正在確認管理員權限…'}catch(e){loginMsg.textContent=e.code==='auth/popup-closed-by-user'?'已取消登入。':(e.message||'登入失敗')}finally{loginBtn.disabled=false;loginBtn.textContent='使用 Google 登入'}}
async function logout(){await auth.signOut();history.replaceState(null,'','#form/'+encodeURIComponent(activeFormId||''));applyRoute()}
function showFront(){history.pushState(null,'','#form/'+encodeURIComponent(activeFormId||''));applyRoute()}

function activeForm(){return forms.find(f=>f.id===activeFormId)||null}

function allowedDepartmentNames(f){let selected=Array.isArray(f.targetDepartments)?f.targetDepartments:[];let all=departments.map(d=>d.name||d.departmentName||d.department||'').filter(Boolean);return selected.length?all.filter(x=>selected.includes(x)):all}
function renderIdentityBlock(f){let deps=allowedDepartmentNames(f);return `<section class="questionCard identityCard"><label class="title">填寫者資料 <span class="required">*</span></label><div class="identityGrid"><label>部門<select id="identityDepartment" required onchange="updateIdentityMembers(this.value)"><option value="">請選擇部門</option>${deps.map(d=>`<option value="${attr(d)}">${esc(d)}</option>`).join('')}</select></label><label>姓名<select id="identityMember" required disabled><option value="">請先選擇部門</option></select></label></div></section>`}
function updateIdentityMembers(department){let select=$('identityMember'),list=members.filter(m=>m.active!==false&&(m.department||m.departmentName||'')===department);select.innerHTML='<option value="">請選擇姓名</option>'+list.map(m=>`<option value="${attr(m.id)}">${esc(m.name)}</option>`).join('');select.disabled=!department}

function renderPublicQuestion(q){let required=q.required?'<span class="required"> *</span>':'';let title=`${esc(q.title||'未命名題目')}${required}`;let help=q.help?`<div class="questionHelp">${esc(q.help)}</div>`:'';let img=imageUrl(q.imageUrl),image=img?`<img class="questionImage" src="${attr(img)}" alt="${attr(q.title||'參考圖片')}">`:'';if(q.type==='image')return `<section class="questionCard"><label class="title">${title}</label>${help}${image}</section>`;let name='q_'+q.id,req=q.required?'required':'';let input='';if(q.type==='long')input=`<textarea name="${attr(name)}" ${req}></textarea>`;else if(q.type==='single'||q.type==='multiple'){let t=q.type==='multiple'?'checkbox':'radio',choiceRequired=q.type==='single'?req:'';input=`<div class="choiceList">${(q.options||[]).map(o=>`<label class="choice"><input type="${t}" name="${attr(name)}" value="${attr(o)}" ${choiceRequired}>${esc(o)}</label>`).join('')}</div>`}else if(q.type==='dropdown'||q.type==='department'){let opts=q.type==='department'?departments.map(d=>d.name||d.departmentName||'').filter(Boolean):(q.options||[]);input=`<select name="${attr(name)}" ${req}><option value="">請選擇</option>${opts.map(o=>`<option value="${attr(o)}">${esc(o)}</option>`).join('')}</select>`}else input=`<input type="text" name="${attr(name)}" ${req}>`;return `<section class="questionCard"><label class="title">${title}</label>${help}${image}${input}</section>`}

async function submitResponse(event){event.preventDefault();let f=activeForm();if(!f||f.state!=='open'||deadlinePassed(f.deadline))return notify('問卷已關閉，請重新整理頁面');let identity={},note=$('submitNote');note.textContent='';note.classList.remove('submitError');if(f.identityMode==='member'){let departmentName=$('identityDepartment')?.value||'',memberId=$('identityMember')?.value||'',m=members.find(x=>x.id===memberId);if(!departmentName||!m)return notify('請選擇您的部門與姓名');if(m.active===false)return notify('這位同仁目前為停用狀態，無法填寫');if((m.department||m.departmentName)!==departmentName)return notify('人員資料與部門不相符，請重新選擇');identity={departmentName,memberId,memberName:m.name||'',employeeNo:m.employeeNo||m.empNo||''}}let fd=new FormData(event.target),answers={};for(let q of(f.questions||[])){if(q.type==='image')continue;let name='q_'+q.id;if(q.type==='multiple')answers[q.id]=fd.getAll(name);else answers[q.id]=String(fd.get(name)||'').trim();if(q.required&&(!answers[q.id]||(Array.isArray(answers[q.id])&&!answers[q.id].length)))return notify('請完成必填題目：'+q.title)}let responseKey=f.identityMode==='member'?`${f.id}__${identity.memberId}`:'',lockRef=responseKey?doc('universalResponseLocks',responseKey):null;if(lockRef){note.textContent='正在確認是否已填寫…';try{let lock=await lockRef.get();if(lock.exists){let message='您已填寫過這份問卷，無法重複送出。如需更正，請洽管理員。';note.textContent=message;note.classList.add('submitError');notify(message,'warn');return}}catch(e){console.error(e);note.textContent='目前無法確認填寫狀態，請稍後再試。';note.classList.add('submitError');notify('無法確認是否已填寫，為避免重複資料，本次不會送出。','error');return}}note.textContent='';if(!await confirmDialog('確認送出這份問卷嗎？送出後如需更正，請洽管理員。','確認送出'))return;let btn=$('submitBtn');btn.disabled=true;btn.textContent='送出中…';setPageLoading(true,'正在送出問卷…');let payload={formId:f.id,formTitle:f.title,...identity,answers,submittedAt:firebase.firestore.FieldValue.serverTimestamp(),submittedAtText:new Date().toLocaleString('zh-TW')};try{let batch=db.batch(),responseRef=responseKey?doc('universalResponses',responseKey):col('universalResponses').doc();batch.set(responseRef,payload);if(lockRef)batch.set(lockRef,{formId:f.id,memberId:identity.memberId,createdAt:firebase.firestore.FieldValue.serverTimestamp()});await batch.commit();frontMain.innerHTML='<div class="successCard submitSuccessCard"><h2>填寫成功</h2><p>已收到您的填寫內容。每位同仁限填一次；如需更正請洽管理員。</p><button class="btn primary" onclick="location.reload()">返回問卷</button></div>';toast('填寫成功','success')}catch(e){console.error(e);if(f.identityMode==='member'&&e.code==='permission-denied'){let message='您已填寫過這份問卷，無法重複送出。如需更正，請洽管理員。';note.textContent=message;note.classList.add('submitError');notify(message,'warn')}else{note.textContent='送出失敗，請稍後再試。';note.classList.add('submitError');notify('送出失敗，請檢查網路後再試一次','error')}btn.disabled=false;btn.textContent='確認並送出'}finally{setPageLoading(false)}}

async function showPanel(id,button){let active=document.querySelector('.panel.active');if(active?.id==='editorPanel'&&id!=='editorPanel'&&formDirty&&!await confirmDialog('問卷內容尚未儲存，確定要離開編輯頁面？','尚未儲存'))return;document.querySelectorAll('.panel').forEach(p=>p.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.nav').forEach(n=>n.classList.remove('active'));if(button)button.classList.add('active');else{let nav=[...document.querySelectorAll('.nav')].find(n=>(n.getAttribute('onclick')||'').includes("'"+id+"'"));if(nav)nav.classList.add('active')}$('panelTitle').textContent=({dashboardPanel:'儀表板',formsPanel:'問卷管理',editorPanel:'問卷編輯',membersPanel:'人員管理',trashPanel:'垃圾桶',permissionsPanel:'權限管理',resultsPanel:'填寫結果'})[id]||'通用問卷後台';if(id==='dashboardPanel')renderDashboard();if(id==='resultsPanel')renderResults();if(id==='membersPanel')renderMemberPanel();if(id==='trashPanel')renderTrash();document.querySelectorAll('.navGroup[open]').forEach(d=>{if(window.innerWidth<900)d.removeAttribute('open')})}
function emptyState(title='尚無資料',desc='目前沒有可顯示的資料。',action=''){return `<div class="emptyState"><span>i</span><b>${esc(title)}</b><p>${esc(desc)}</p>${action}</div>`}
function table(headers,rows,emptyHtml=''){return `<div class="tableWrap dataTable"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.join('')||`<tr><td class="emptyCell" colspan="${headers.length}">${emptyHtml||emptyState()}</td></tr>`}</tbody></table></div>`}
function effectiveState(form){if(!form?.deleted&&form?.state==='open'&&deadlinePassed(form.deadline))return'expired';return form?.deleted?'deleted':form?.state||'draft'}
function stateLabel(v){return({draft:'草稿',open:'開放填寫',closed:'已關閉',deleted:'已移至垃圾桶',expired:'已截止',pending:'尚未開始'})[v]||v}
function statePillHtml(state){return `<span class="statePill state-${attr(state||'draft')}">${esc(stateLabel(state))}</span>`}
function countPillHtml(count){return `<span class="countPill">${Number(count)||0}</span>`}
function roleBadgeHtml(role,canManage=false){let cls=canManage?'manager':'viewer';return `<span class="roleBadge ${cls}">${esc(role)}</span>`}
function actionButton(label,handler,variant=''){return `<button class="btn ${variant}" onclick="${attr(handler)}">${esc(label)}</button>`}
function actionGroup(buttons){return `<div class="buttonRow tableActions">${buttons.filter(Boolean).join('')}</div>`}
function moreActions(buttons){let html=buttons.filter(Boolean).join('');return html?`<details class="moreMenu"><summary class="btn">更多</summary><div>${html}</div></details>`:''}

function renderTargetDepartments(selected=null){if(selected===null)selected=[...document.querySelectorAll('.targetDepartment:checked')].map(x=>x.value);let enabled=$('identityMode').value==='member',box=$('targetDepartmentBox');box.innerHTML=departments.map(d=>{let n=d.name||d.departmentName||d.department||'';return `<label class="departmentChoice"><input type="checkbox" class="targetDepartment" value="${attr(n)}" ${selected.includes(n)?'checked':''}>${esc(n)}</label>`}).join('')||'<span class="questionHelp">尚無部門資料</span>';document.querySelector('.identitySettings')?.classList.toggle('disabled',!enabled);box.querySelectorAll('input').forEach(x=>x.disabled=!enabled)}
function startNewForm(){formDirty=false;editMode='new';editingId='';draftQuestions=[];$('editorHeading').textContent='新增問卷';$('editorMode').textContent='新增模式';$('saveFormBtn').textContent='建立問卷';$('formTitle').value='';$('formDescription').value='';$('formDeadline').value='';$('formState').value='draft';$('formImageUrl').value='';previewHeaderImage();$('identityMode').value='member';renderTargetDepartments([]);renderQuestionEditor()}
function editForm(id){let f=forms.find(x=>x.id===id);if(!f)return;formDirty=false;editMode='edit';editingId=id;draftQuestions=JSON.parse(JSON.stringify(f.questions||[]));$('editorHeading').textContent='編輯問卷：'+f.title;$('editorMode').textContent='編輯模式';$('saveFormBtn').textContent='儲存變更';$('formTitle').value=f.title||'';$('formDescription').value=f.description||'';$('formDeadline').value=(f.deadline||'').slice(0,16);$('formState').value=f.state||'draft';$('formImageUrl').value=f.imageUrl||'';previewHeaderImage();$('identityMode').value=f.identityMode||'none';renderTargetDepartments(f.targetDepartments||[]);renderQuestionEditor();showPanel('editorPanel')}
function cancelEdit(){formDirty=false;showPanel('formsPanel');startNewForm()}
function addQuestion(type='short'){draftQuestions.push({id:'q_'+Date.now()+'_'+Math.random().toString(36).slice(2,6),type,title:'',required:false,options:[],imageUrl:'',help:''});renderQuestionEditor()}
function updateQuestion(i,key,value){if(key==='options')draftQuestions[i][key]=value.split('\n').map(x=>x.trim()).filter(Boolean);else draftQuestions[i][key]=value}
function moveQuestion(i,delta){let j=i+delta;if(j<0||j>=draftQuestions.length)return;[draftQuestions[i],draftQuestions[j]]=[draftQuestions[j],draftQuestions[i]];renderQuestionEditor()}
async function removeQuestion(i){if(await confirmDialog('確定移除此題？','移除題目',true)){draftQuestions.splice(i,1);renderQuestionEditor()}}
function renderQuestionEditor(){questionEditor.innerHTML=draftQuestions.map((q,i)=>`<div class="questionEdit"><div class="questionGrid"><label>題目名稱<input value="${attr(q.title)}" oninput="updateQuestion(${i},'title',this.value)"></label><label>題型<select onchange="updateQuestion(${i},'type',this.value);renderQuestionEditor()">${[['short','簡答'],['long','長文'],['single','單選'],['multiple','複選'],['dropdown','下拉選單'],['department','部門選單'],['image','圖片／說明']].map(x=>`<option value="${x[0]}" ${q.type===x[0]?'selected':''}>${x[1]}</option>`).join('')}</select></label><label>必填<select onchange="updateQuestion(${i},'required',this.value==='true')"><option value="false" ${!q.required?'selected':''}>否</option><option value="true" ${q.required?'selected':''}>是</option></select></label></div>${['single','multiple','dropdown'].includes(q.type)?`<label class="optionsField">選項（每行一個）<textarea oninput="updateQuestion(${i},'options',this.value)">${esc((q.options||[]).join('\n'))}</textarea></label>`:''}<div class="questionGrid"><label>說明文字<input value="${attr(q.help||'')}" oninput="updateQuestion(${i},'help',this.value)"></label><div class="questionImageField"><label>參考圖片網址<input value="${attr(q.imageUrl||'')}" placeholder="可貼 Google Drive 分享網址" oninput="updateQuestionImage(${i},this.value)"></label><p>Drive 圖片需開啟「知道連結的使用者皆可查看」。</p><div id="questionImagePreview_${i}" class="imagePreview">${imagePreviewHtml(q.imageUrl,q.title||'參考圖片預覽')}</div></div></div><div class="miniActions"><button class="btn" onclick="moveQuestion(${i},-1)">上移</button><button class="btn" onclick="moveQuestion(${i},1)">下移</button><button class="btn danger" onclick="removeQuestion(${i})">移除</button></div></div>`).join('')||'<div class="questionHelp">尚未建立題目，請按「新增題目」。</div>'}

async function saveForm(){let title=$('formTitle').value.trim();if(!title)return notify('請輸入問卷標題');if(!draftQuestions.length)return notify('請至少建立一個題目');if(draftQuestions.some(q=>!q.title.trim()))return notify('每一題都需要題目名稱');if(draftQuestions.some(q=>['single','multiple','dropdown'].includes(q.type)&&!(q.options||[]).length))return notify('選擇題至少需要一個選項');let identityMode=$('identityMode').value,targetDepartments=identityMode==='member'?[...document.querySelectorAll('.targetDepartment:checked')].map(x=>x.value):[];if(identityMode==='member'&&!targetDepartments.length)return notify('請至少選擇一個開放填寫部門');let id=editMode==='edit'?editingId:'form_'+Date.now(),data={title,description:$('formDescription').value.trim(),deadline:$('formDeadline').value,state:$('formState').value,imageUrl:$('formImageUrl').value.trim(),identityMode,targetDepartments,questions:draftQuestions,updatedAt:firebase.firestore.FieldValue.serverTimestamp(),updatedByEmail:normalizeEmail(currentUser?.email||'')};if(editMode==='new'){data.createdAt=firebase.firestore.FieldValue.serverTimestamp();data.createdByEmail=normalizeEmail(currentUser?.email||'');data.createdByName=currentUser?.displayName||currentUser?.email||''}let btn=$('saveFormBtn');btn.disabled=true;btn.textContent='儲存中…';setPageLoading(true,'正在儲存問卷…');try{await doc('universalForms',id).set(data,{merge:true});formDirty=false;activeFormId=id;await loadAdminData();showPanel('formsPanel');toast(editMode==='edit'?'問卷變更已儲存':'問卷已建立','success')}catch(e){console.error(e);notify('問卷儲存失敗，請確認權限或網路狀態','error')}finally{setPageLoading(false);btn.disabled=false;btn.textContent=editMode==='edit'?'儲存變更':'建立問卷'}}
function formRoleLabel(f){if(isSystemAdmin)return isCreatedByCurrentUser(f)?'發起人':'系統管理員';if(isCreatedByCurrentUser(f))return'發起人';let a=assignmentFor(f.id);return a?.role==='manager'?'問卷管理者':'檢視者'}
function responseCountForForm(formId){return formId===activeFormId?responses.length:(forms.find(f=>f.id===formId)?.responseCount||0)}
function formsBySection(){let list=accessibleForms(),open=list.filter(f=>f.deleted!==true&&effectiveState(f)!=='closed'&&effectiveState(f)!=='expired'),mine=open.filter(isCreatedByCurrentUser),shared=open.filter(f=>!isCreatedByCurrentUser(f)&&!!assignmentFor(f.id)),closed=list.filter(f=>f.deleted!==true&&(effectiveState(f)==='closed'||effectiveState(f)==='expired')),all=isSystemAdmin?forms.filter(f=>f.deleted!==true):[];return[{title:'我建立的問卷',hint:'由目前登入帳號建立，可直接管理內容與填寫結果。',items:mine},{title:'被分享的問卷',hint:'由其他管理者分享給您的問卷，依指派權限可管理或檢視。',items:shared},{title:'已關閉的問卷',hint:'已關閉或已截止的問卷集中在此，方便查詢歷史資料。',items:closed},...(isSystemAdmin?[{title:'系統內所有問卷',hint:'系統管理員可查看所有未刪除問卷與建立者紀錄。',items:all}]:[])]}
function adminRouteId(){let m=location.hash.match(/^#admin\/([^/?#]+)/);return m?decodeURIComponent(m[1]):''}

async function loadPublicData(){let[fs,ds,ms]=await Promise.all([col('universalForms').get(),col('departments').get(),col('members').get()]);forms=fs.docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>(b.createdAt?.seconds||0)-(a.createdAt?.seconds||0));departments=ds.docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>(a.sortOrder??999)-(b.sortOrder??999));let depOrder=new Map(departments.map((d,i)=>[d.name||d.departmentName||d.department||'',i]));members=ms.docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>{let ad=a.department||a.departmentName||'',bd=b.department||b.departmentName||'',diff=(depOrder.get(ad)??9999)-(depOrder.get(bd)??9999);if(diff)return diff;return String(a.employeeNo||a.empNo||'').localeCompare(String(b.employeeNo||b.empNo||''),'zh-Hant',{numeric:true})||String(a.name||'').localeCompare(String(b.name||''),'zh-Hant')});let publicForms=forms.filter(f=>f.deleted!==true),route=formRouteId(),adminId=adminRouteId(),allowed=isAdmin?accessibleForms():[];if(adminId&&allowed.some(f=>f.id===adminId))activeFormId=adminId;else if(route&&publicForms.some(f=>f.id===route))activeFormId=route;else if(isAdmin&&allowed.length&&!allowed.some(f=>f.id===activeFormId))activeFormId=allowed[0].id;else if(!isAdmin&&!publicForms.some(f=>f.id===activeFormId))activeFormId=(publicForms.find(f=>f.state==='open')||publicForms[0])?.id||''}
async function loadAdminData(){await loadPublicData();await loadMemberAccounts();if(isSystemAdmin&&!submissionLocksPrepared)await prepareSubmissionLocks();await loadResponses();renderAdmin()}
async function loadResponses(){if(!isAdmin||!activeFormId||!canViewForm(activeFormId)){responses=[];return}try{let q=await col('universalResponses').where('formId','==',activeFormId).get();responses=q.docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>(b.submittedAt?.seconds||0)-(a.submittedAt?.seconds||0))}catch(e){console.warn(e);responses=[]}}
function applyRoute(){let wantsAdmin=location.hash==='#admin'||location.hash.startsWith('#admin/');if(wantsAdmin&&isAdmin){front.style.display='none';admin.style.display='block';loginMask.style.display='none';let routeId=adminRouteId();if(routeId&&canViewForm(routeId)&&routeId!==activeFormId){activeFormId=routeId;loadResponses().then(renderAdmin);return}renderAdmin();return}admin.style.display='none';front.style.display='block';loginMask.style.display=wantsAdmin&&!isAdmin?'grid':'none';renderFront();if(loginPurpose==='response'&&currentUser)setTimeout(showMyResponse,0)}
function myResponseButton(f){return f?.identityMode==='member'?'<button class="ghostBtn" type="button" onclick="startMyResponseView()">查看我的填寫結果</button>':''}
function renderFront(){let publicForms=forms.filter(x=>x.deleted!==true),f=publicForms.find(x=>x.id===(formRouteId()||activeFormId))||publicForms.find(x=>x.state==='open')||publicForms[0];if(!f){formStatus.textContent='尚無問卷';frontMain.innerHTML='<div class="successCard"><h2>目前尚無可填寫問卷</h2><p>請洽管理者建立問卷。</p></div>';return}activeFormId=f.id;let closed=f.state!=='open'||deadlinePassed(f.deadline);formStatus.textContent=closed?'問卷已關閉':'問卷開放中';let actions=document.querySelector('.frontActions');if(actions)actions.innerHTML=`<span id="formStatus" class="statusPill">${closed?'問卷已關閉':'問卷開放中'}</span>${myResponseButton(f)}<button class="ghostBtn" onclick="openAdmin()">管理登入</button>`;let heroImage=imageUrl(f.imageUrl);frontMain.innerHTML=`<section class="formHero"><h1>${esc(f.title)}</h1><p>${esc(f.description||'')}</p>${f.deadline?`<span class="deadlineBadge">請於 ${esc(formatDeadline(f.deadline))} 前完成</span>`:''}${heroImage?`<img class="referenceImage" src="${attr(heroImage)}" alt="問卷參考圖片">`:''}</section><div id="myResponseBox"></div>${closed?'<div class="successCard" style="margin-top:18px"><h2>本問卷目前未開放填寫</h2></div>':`<form id="publicForm" class="questionList" onsubmit="submitResponse(event)">${f.identityMode==='member'?renderIdentityBlock(f):''}${(f.questions||[]).map(renderPublicQuestion).join('')}<div class="submitArea"><button id="submitBtn" class="btn primary" type="submit">確認並送出</button><span id="submitNote" class="questionHelp"></span></div></form>`}`}

async function startMyResponseView(){loginPurpose='response';loginMsg.textContent='';if(!currentUser){loginMask.style.display='grid';return}await loadMemberAccounts();await showMyResponse()}
async function showMyResponse(){let box=$('myResponseBox'),f=activeForm();if(!box||!f)return;let member=findMemberByGoogleEmail(currentUser?.email||'');if(!member){box.innerHTML='<div class="notice myResponseCard">找不到此 Google 帳號對應的人員資料，請確認是否使用公司行事曆同一組帳號。</div>';return}box.innerHTML='<div class="notice myResponseCard">正在讀取您的填寫內容…</div>';try{let snap=await doc('universalResponses',`${f.id}__${member.id}`).get();if(!snap.exists){box.innerHTML='<div class="notice myResponseCard">目前查無您的填寫紀錄。</div>';return}let r={id:snap.id,...snap.data()},questions=(f.questions||[]).filter(q=>q.type!=='image'),answers=questions.map(q=>`<div class="myAnswerItem"><b>${esc(q.title||'未命名題目')}</b><p>${esc(answerText(q,r)||'未填')}</p></div>`).join('');box.innerHTML=`<section class="notice myResponseCard"><h2>我的填寫結果</h2><p class="myResponseMeta"><span>${esc(r.departmentName||member.department||'')}</span><span>${esc(r.memberName||member.name||'')}</span><span>${esc(r.employeeNo||member.employeeNo||member.empNo||'')}</span><span>${esc(r.submittedAtText||'')}</span></p><div class="myAnswerList">${answers||'<div class="myAnswerItem"><p>此問卷沒有可顯示的題目。</p></div>'}</div></section>`}catch(e){console.error(e);box.innerHTML='<div class="notice myResponseCard">讀取失敗，請確認 Firestore 規則已部署 v1.24 完整合併版。</div>'}}

function renderShareMemberOptions(){let select=$('managerEmail');if(!select)return;let current=select.value,options=members.filter(m=>m.active!==false&&memberGoogleEmail(m)).map(m=>({email:memberGoogleEmail(m),label:memberDisplayName(m)||m.name||m.id}));select.innerHTML='<option value="">請選擇成員</option>'+options.map(x=>`<option value="${attr(x.email)}">${esc(x.label)}</option>`).join('');select.value=options.some(x=>x.email===current)?current:''}
function managerPersonLabel(email){let member=findMemberByGoogleEmail(email),label=memberDisplayName(member);return label?`<b>${esc(label)}</b>`:`<b class="muted">未對應人員</b>`}
function ensureAdminExtensions(){if(!$('permissionsPanel')){$('resultsPanel')?.insertAdjacentHTML('beforebegin',`<section id="permissionsPanel" class="panel"><div class="card"><div class="sectionHead"><div><h2>問卷權限管理</h2><p>針對目前選取的問卷分享管理或檢視權限；問卷管理者可編輯問卷與回覆，檢視者只能查看與匯出。</p></div></div><div class="permissionForm"><label>分享成員<select id="managerEmail"><option value="">請選擇成員</option></select><small class="questionHelp">Google 帳號係同仁部門行事曆使用之帳號；如帳號異動，請洽系統管理員修正後方可登入。</small></label><label>權限<select id="managerRole"><option value="manager">問卷管理者</option><option value="viewer">結果檢視者</option></select></label><button class="btn primary" onclick="saveFormManager()">新增／更新權限</button></div><div id="formManagersTable"></div></div></section>`)}renderShareMemberOptions()}
function updateRoleUi(){ensureAdminExtensions();let navs=[...document.querySelectorAll('.sidebar .nav')];navs.forEach(n=>{let t=n.textContent.trim();if(t==='人員管理'||t==='垃圾桶')n.style.display=isSystemAdmin?'':'none'});$('permissionsNav').style.display=activeFormId&&canManageForm(activeFormId)?'':'none';let groups=document.querySelectorAll('.navGroup');if(groups[1])groups[1].style.display=isSystemAdmin?'':'none';[...document.querySelectorAll('#formsPanel button')].filter(b=>/外套尺寸範本/.test(b.textContent)).forEach(b=>b.style.display=isSystemAdmin?'':'none');if(!isSystemAdmin&&($('membersPanel')?.classList.contains('active')||$('trashPanel')?.classList.contains('active')))showPanel('dashboardPanel');if(activeFormId&&!canManageForm(activeFormId)&&($('editorPanel')?.classList.contains('active')||$('permissionsPanel')?.classList.contains('active')))showPanel('resultsPanel')}
function renderDashboard(){let f=activeForm(),progress=f?.identityMode==='member'?completionData(f):null,rate=progress&&progress.expected.length?Math.round(progress.filled.length*1000/progress.expected.length)/10:null;if($('dashResponseCount'))$('dashResponseCount').textContent=f?responses.length:0;if($('dashExpectedCount'))$('dashExpectedCount').textContent=progress?progress.expected.length:'—';if($('dashCompletionRate'))$('dashCompletionRate').textContent=rate!==null?`${rate}%`:'—';if($('dashMissingCount'))$('dashMissingCount').textContent=progress?progress.missing.length:'—';if($('dashCurrentNote'))$('dashCurrentNote').textContent=f?`${f.title}：${stateLabel(effectiveState(f))}，截止 ${formatDeadline(f.deadline)||'未設定'}`:'請先選擇問卷。';if($('dashboardCurrent'))$('dashboardCurrent').innerHTML=f?`<div class="currentSurveyCard"><h3>${esc(f.title)}</h3><p>${esc(f.description||'尚未填寫問卷說明')}</p><div class="currentSurveyMeta"><span>${statePillHtml(effectiveState(f))}</span><span>開始時間 ${esc(formStartLabel(f))}</span><span>截止時間 ${esc(formatDeadline(f.deadline)||'未設定')}</span><span>建立者 ${esc(formCreatorLabel(f))}</span><span>我的角色 ${roleBadgeHtml(formRoleLabel(f),canManageForm(f.id))}</span><span>填寫進度 ${progress?`${progress.filled.length}/${progress.expected.length}`:'未設定'}</span></div></div>`:emptyState('尚未選擇問卷','請先從右上角選擇問卷，或建立新的問卷。',`<button class="btn primary" onclick="showPanel('editorPanel');startNewForm()">建立問卷</button>`)}
function renderAdmin(){ensureAdminExtensions();let list=accessibleForms();if(list.length&&!list.some(f=>f.id===activeFormId))activeFormId=list[0].id;activeFormSelect.innerHTML='<option value="">請選擇問卷</option>'+list.map(f=>`<option value="${attr(f.id)}" ${f.id===activeFormId?'selected':''}>${esc(f.title)}</option>`).join('');let f=activeForm();activeFormLabel.textContent=f?'目前問卷：'+f.title:'尚未選擇問卷';$('formCount').textContent=list.length;$('currentFormName').textContent=f?.title||'—';$('responseCount').textContent=responses.length;renderDashboard();renderFormsTable();if(isSystemAdmin){renderMemberPanel();renderTrash();if($('permissionsPanel')?.classList.contains('active'))loadFormManagers()}renderResults();updateRoleUi()}
function formRowHtml(f){let manage=canManageForm(f.id),id=attr(f.id),role=formRoleLabel(f),more=[actionButton('前台',`copyFormLink('${id}')`),actionButton('後台',`copyAdminLink('${id}')`),manage?actionButton('權限',`openPermissions('${id}')`):'',manage?actionButton('移至垃圾桶',`deleteForm('${id}')`,'danger'):''];let buttons=[manage?actionButton('編輯',`editForm('${id}')`):'',actionButton('結果',`openResults('${id}')`),actionButton('複製',`copyFormLink('${id}')`),moreActions(more)];return `<tr><td><b>${esc(f.title)}</b><br><small>${esc(f.id)}</small></td><td>${esc(formCreatorLabel(f))}</td><td>${esc(formatDeadline(f.deadline)||'未設定')}</td><td>${roleBadgeHtml(role,manage||role==='發起人')}</td><td>${countPillHtml((f.questions||[]).length)}</td><td>${countPillHtml(responseCountForForm(f.id))}</td><td>${statePillHtml(effectiveState(f))}</td><td>${actionGroup(buttons)}</td></tr>`}
function renderFormsTable(){let sections=formsBySection();formsTable.innerHTML=sections.map(section=>`<div class="surveyGroup"><div class="surveyGroupHead"><h3>${esc(section.title)}</h3><span>${section.items.length}</span></div><p>${esc(section.hint)}</p>${table(['問卷名稱','建立者','問卷期間','我的角色','題目數','填寫份數','狀態','操作'],section.items.map(formRowHtml),emptyState('尚無問卷','此分類目前沒有可顯示的問卷。'))}</div>`).join('')}
async function selectForm(id){if(!id||!canViewForm(id))return;activeFormId=id;history.replaceState(null,'','#admin/'+encodeURIComponent(id));await loadResponses();renderAdmin()}
async function openResults(id){await selectForm(id);showPanel('resultsPanel')}
async function openPermissions(id){await selectForm(id);showPanel('permissionsPanel');await loadFormManagers()}
function openMissingList(){showPanel('resultsPanel');let panel=ensureMissingPanel();if(panel)panel.scrollIntoView({behavior:'smooth',block:'start'})}
async function copyAdminLink(id=activeFormId){if(!id)return notify('請先選擇問卷');let url=location.href.split('#')[0]+'#admin/'+encodeURIComponent(id);if(navigator.clipboard?.writeText)try{await navigator.clipboard.writeText(url);toast('專屬後台網址已複製','success');return}catch(e){}await showCopyDialog('複製專屬後台網址',url)}


async function deleteForm(id){if(!canManageForm(id))return notify('您沒有刪除此問卷的權限','error');let f=forms.find(x=>x.id===id);if(!f)return;setPageLoading(true,'正在讀取回覆數…');let snap;try{snap=await col('universalResponses').where('formId','==',id).get()}finally{setPageLoading(false)}let count=snap.size,typed=await inputConfirmDialog({title:'移至垃圾桶',message:`即將把問卷移至垃圾桶：\n${f.title}\n目前共有 ${count} 份回覆。\n\n移至垃圾桶後前台不再顯示，但資料仍可復原。`,requiredText:f.title,danger:true});if(typed===null)return;setPageLoading(true,'正在移至垃圾桶…');try{await doc('universalForms',id).set({deleted:true,deletedAt:firebase.firestore.FieldValue.serverTimestamp(),deletedBy:currentUser?.email||''},{merge:true});if(activeFormId===id)activeFormId='';await loadAdminData();showPanel('formsPanel');toast('問卷已移至垃圾桶','success')}catch(e){console.error(e);notify('移至垃圾桶失敗，請確認權限或網路狀態','error')}finally{setPageLoading(false)}}
function renderTrash(){let deleted=forms.filter(f=>f.deleted===true);$('trashTable').innerHTML=table(['問卷名稱','刪除時間','刪除者','原建立者','回覆數','操作'],deleted.map(f=>{let id=attr(f.id);return `<tr><td><b>${esc(f.title)}</b><br><small>${esc(f.id)}</small></td><td>${esc(f.deletedAt?.toDate?f.deletedAt.toDate().toLocaleString('zh-TW'):'未紀錄')}</td><td>${esc(f.deletedBy||'未紀錄')}</td><td>${esc(formCreatorLabel(f))}</td><td>${countPillHtml(responseCountForForm(f.id))}</td><td>${actionGroup([actionButton('復原',`restoreForm('${id}')`),actionButton('永久刪除',`permanentlyDeleteForm('${id}')`,'danger')])}</td></tr>`}),emptyState('垃圾桶是空的','目前沒有移至垃圾桶的問卷。'))}
async function restoreForm(id){if(!isSystemAdmin)return;await doc('universalForms',id).update({deleted:false,deletedAt:firebase.firestore.FieldValue.delete(),deletedBy:firebase.firestore.FieldValue.delete()});await loadAdminData();toast('問卷已復原')}
async function deleteSnapshotInChunks(snapshot){let docs=snapshot.docs;for(let i=0;i<docs.length;i+=400){let batch=db.batch();docs.slice(i,i+400).forEach(x=>batch.delete(x.ref));await batch.commit()}}
async function permanentlyDeleteForm(id){if(!isSystemAdmin)return notify('只有系統管理員可以永久刪除問卷','error');let f=forms.find(x=>x.id===id);if(!f)return;setPageLoading(true,'正在讀取關聯資料…');let responseSnap;try{responseSnap=await col('universalResponses').where('formId','==',id).get()}finally{setPageLoading(false)}let typed=await inputConfirmDialog({title:'永久刪除問卷',message:`永久刪除後無法復原。\n問卷：${f.title}\n回覆：${responseSnap.size} 份`,requiredText:f.title,danger:true});if(typed===null)return;setPageLoading(true,'正在永久刪除問卷與關聯資料…');try{let[lockSnap,managerSnap]=await Promise.all([col('universalResponseLocks').where('formId','==',id).get(),col('universalFormManagers').where('formId','==',id).get()]);await deleteSnapshotInChunks(responseSnap);await deleteSnapshotInChunks(lockSnap);await deleteSnapshotInChunks(managerSnap);await doc('universalForms',id).delete();await loadAdminData();toast('問卷及其回覆已永久刪除','success')}catch(e){console.error(e);notify('永久刪除失敗，請確認權限或網路狀態','error')}finally{setPageLoading(false)}}


async function loadFormManagers(){if(!activeFormId||!canManageForm(activeFormId))return;$('formManagersTable').innerHTML='<p class="questionHelp loadingBox">讀取中…</p>';try{let q=await col('universalFormManagers').where('formId','==',activeFormId).get();formManagers=q.docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>String(a.email).localeCompare(String(b.email)));renderFormManagers()}catch(e){console.error(e);$('formManagersTable').innerHTML='<p class="errorText">無法讀取權限資料，請確認已發布 v1.24 Firestore 規則。</p>'}}
function renderFormManagers(){$('formManagersTable').innerHTML=table(['分享成員','權限','狀態','操作'],formManagers.map(m=>{let id=attr(m.id),enabled=m.enabled!==false;return `<tr><td><b>${esc(managerPersonLabel(m.email))}</b><br><small>${esc(m.email||'')}</small></td><td>${roleBadgeHtml(m.role==='manager'?'問卷管理者':'結果檢視者',m.role==='manager')}</td><td><span class="statePill ${enabled?'state-open':'state-closed'}">${enabled?'啟用':'停用'}</span></td><td>${actionGroup([actionButton(enabled?'停用':'啟用',`toggleFormManager('${id}',${enabled?'false':'true'})`),actionButton('移除',`removeFormManager('${id}')`,'danger')])}</td></tr>`}),emptyState('尚無分享成員','此問卷尚未分享給其他成員。'))}
function managerDocumentId(formId,email){return formId+'__'+String(email).trim().toLowerCase()}
async function saveFormManager(){if(!activeFormId||!canManageForm(activeFormId))return toast('您沒有管理此問卷權限','error');let email=normalizeEmail($('managerEmail').value),role=$('managerRole').value;if(!/^\S+@\S+\.\S+$/.test(email))return toast('請選擇分享成員','warn');let member=findMemberByGoogleEmail(email);if(!member)return toast('請從分享成員清單選擇人員','warn');let id=managerDocumentId(activeFormId,email),existing=formManagers.find(x=>x.id===id),data={formId:activeFormId,email,role,enabled:true,memberId:member.id||'',displayName:memberDisplayName(member),updatedAt:firebase.firestore.FieldValue.serverTimestamp()};if(!existing)data.createdAt=firebase.firestore.FieldValue.serverTimestamp();await doc('universalFormManagers',id).set(data,{merge:true});$('managerEmail').value='';await loadFormManagers();toast(existing?'權限已更新':'已新增問卷權限','success')}
async function toggleFormManager(id,enabled){if(!activeFormId||!canManageForm(activeFormId))return;await doc('universalFormManagers',id).set({enabled,updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});await loadFormManagers();toast(enabled?'權限已啟用':'權限已停用','success')}
async function removeFormManager(id){if(!activeFormId||!canManageForm(activeFormId))return;let m=formManagers.find(x=>x.id===id),label=(m?.displayName||managerPersonLabel(m?.email)||m?.email||'此帳號').replace(/<[^>]*>/g,'');if(!await confirmDialog(`確定移除 ${label} 的問卷權限？`,'移除權限',true))return;setPageLoading(true,'正在移除權限…');try{await doc('universalFormManagers',id).delete();await loadFormManagers();toast('問卷權限已移除','success')}catch(e){console.error(e);notify('移除權限失敗，請確認權限或網路狀態','error')}finally{setPageLoading(false)}}

function renderResults(){let f=activeForm(),progress=f?.identityMode==='member'?completionData(f):null;$('resultCaption').textContent=f?`${f.title}：共 ${responses.length} 份回覆${progress?`；應填 ${progress.expected.length} 人，未填 ${progress.missing.length} 人`:''}`:'請先選擇問卷。';if(!f){$('resultAnalysis').innerHTML='';resultsTable.innerHTML='';let p=$('missingResponsesPanel');if(p)p.style.display='none';return}$('resultAnalysis').innerHTML=renderAnalysis(f);renderMissingMembers(f);let qs=(f.questions||[]).filter(q=>q.type!=='image'),identityHeaders=f.identityMode==='member'?['部門','姓名','員工編號']:[],manage=canManageForm(f.id);resultsTable.innerHTML=table(['送出時間',...identityHeaders,...qs.map(q=>q.title),'操作'],responses.map(r=>{let id=attr(r.id),actions=manage?actionGroup([actionButton('編輯',`openResponseEditor('${id}')`),actionButton('刪除',`deleteResponse('${id}')`,'danger')]):roleBadgeHtml('唯讀',false);return `<tr><td>${esc(r.submittedAtText||'')}</td>${f.identityMode==='member'?`<td>${esc(r.departmentName||'')}</td><td>${esc(r.memberName||'')}</td><td>${esc(r.employeeNo||'')}</td>`:''}${qs.map(q=>`<td>${esc(answerText(q,r))}</td>`).join('')}<td>${actions}</td></tr>`}))}

init().catch(e=>{console.error(e);frontMain.innerHTML='<div class="successCard"><h2>系統載入失敗</h2><p>'+esc(e.message||e)+'</p></div>'});







